// <auto-generated />
using System;
using BettingControl.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettingControl.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018013310_InitialMigrationWithAllEntities")]
    partial class InitialMigrationWithAllEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BettingControl.API.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campeonato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CicloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Continente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAposta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LucroPrejuizo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mercado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Odd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Resultado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeCasa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeVisitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorApostado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CicloId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BettingControl.API.Models.Ciclo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LucroPrejuizo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROI")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalApostado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalGanhos")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ciclos");
                });

            modelBuilder.Entity("BettingControl.API.Models.FechamentoMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LucroPrejuizo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROI")
                        .HasColumnType("TEXT");

                    b.Property<string>("SugestoesAnalise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaAcerto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalApostado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalGanhos")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Yield")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FechamentosMensais");
                });

            modelBuilder.Entity("BettingControl.API.Models.HistoricoBanca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HistoricoBancas");
                });

            modelBuilder.Entity("BettingControl.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BettingControl.API.Models.Bet", b =>
                {
                    b.HasOne("BettingControl.API.Models.Ciclo", "Ciclo")
                        .WithMany("Bets")
                        .HasForeignKey("CicloId");

                    b.Navigation("Ciclo");
                });

            modelBuilder.Entity("BettingControl.API.Models.Ciclo", b =>
                {
                    b.HasOne("BettingControl.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BettingControl.API.Models.FechamentoMensal", b =>
                {
                    b.HasOne("BettingControl.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BettingControl.API.Models.HistoricoBanca", b =>
                {
                    b.HasOne("BettingControl.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BettingControl.API.Models.Ciclo", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
